version: '3'
services:
  # oneday_backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: oneday_backend
  #   env_file:
  #     - .env
  #   command: npm run start:dev
  #   ports:
  #     - '8001:8001'
  #   depends_on:
  #     - oneday_database
  #   networks:
  #     - oneday-network

  oneday_database:
    container_name: oneday_databases
    image: postgres:latest
    ports:
      - '5432:5432'
    env_file:
      - .env
    # networks:
    #   - oneday-network
# networks:
#   oneday-network:
#     driver: bridge
